/**
 * @file regex.ts
 * @description 国际化语言包子模块（由 index.ts 拆分生成）
 */

const regexCreationModal = {
  title: 'Create Regular Expression',
  name: 'Regex Name',
  pattern: 'Regex Pattern',
  description: 'Description',
  testString: 'Test String',
  testResult: 'Test Result',
  isValid: 'Valid',
  isInvalid: 'Invalid',
  save: 'Save',
  cancel: 'Cancel',
  ruleNameRequired: 'Please enter rule name',
  regexRequired: 'Please enter regex pattern',
}

const regexDesignModal = {
  title: 'Regex Design',
  selectOrAddRule: 'Select or add a rule',
  addRule: 'Add Rule',
  autoSaveTip: 'Auto-save enabled',
  cancel: 'Cancel',
  save: 'Save',
}

const expression = {
  title: 'Expression Editor',
  interactiveBuilder: 'Interactive Builder',
  paramDefinition: 'Parameter Definition',
  ruleConfig: 'Rule Configuration',
  ruleList: 'Rule List',
  ruleTest: 'Rule Testing',
  selectionPopover: 'Selection Popover',
}

const expressions = {
  selectionPopover: {
    setAsParameter: 'Set as Parameter',
    cancelSelection: 'Cancel Selection',
  },
  interactiveBuilder: {
    inputText: 'Input Text',
    exampleText: 'e.g.: Order Amount > 100',
    previewSelection: 'Preview Selection',
    previewHere: 'Preview here...',
  },
  ruleConfigPanel: {
    ruleConfig: 'Rule Configuration',
    saveAllRules: 'Save All Rules',
    ruleDefinition: 'Rule Definition',
    ruleName: 'Rule Name',
    ruleNamePlaceholder: 'Give your rule a name',
    interactiveBuilder: 'Interactive Builder',
    regex: 'Regular Expression',
    regexPlaceholder: 'Generated by builder or manually entered',
    regexHint: 'Generated by builder or manually edited',
    outputMapping: 'Output Mapping',
    outputMappingHint:
      'Key becomes the final derived column name. Use meaningful names (often the group name).',
    outputTemplate: 'Output Template',
    clickToAddFirst: 'Click the button below to add your first output key-value pair',
    key: 'Key',
    selectParameter: 'Select Parameter',
    staticValue: 'Static Value',
    staticValuePlaceholder: 'Enter static text...',
    bindToParam: 'Bind to regex variable',
    noNamedGroups: '(No named capture groups)',
    deleteThisRow: 'Delete This Row',
    addKeyValue: 'Add Key-Value Pair',
    keyAlreadyExists: 'Key "{key}" already exists, please use a unique key name.',
  },
  paramDefinitionModal: {
    defineParameter: 'Define Parameter',
    closeModal: 'Close Modal',
    parameterName: 'Parameter Name',
    parameterNamePlaceholder: 'e.g.: amount',
    parameterType: 'Parameter Type',
    typeInt: 'Integer (int)',
    typeFloat: 'Float (float)',
    typeWord: 'Word (word)',
    typeNonSpace: 'Non-space (non_space)',
    typeAnything: 'Anything (anything)',
    cancel: 'Cancel',
    confirm: 'Confirm',
    paramNameCannotBeEmpty: 'Parameter name cannot be empty!',
  },
  ruleTestPanel: {
    realTimeTest: 'Real-time Test',
    testString: 'Test String',
    testStringPlaceholder: 'Enter text to test here',
    matchStatus: 'Match Status',
    matchSuccess: 'Match Success',
    matchFailed: 'Match Failed',
    waitingForInput: 'Waiting for input...',
    captureGroups: 'Capture Groups',
    errorMessage: 'Error Message',
  },
  ruleList: {
    patterns: 'Patterns (Combination Rules)',
    addPattern: 'Add Pattern',
    atomicPatterns: 'Atomic Patterns',
    addAtomicPattern: 'Add Atomic Pattern',
  },
}

export { regexCreationModal }
export { regexDesignModal }
export { expression }
export { expressions }
