import type { Component } from 'vue'
import {
  Archive,
  ArrowRight,
  Ban,
  BellOff,
  Binary,
  Boxes,
  Brush,
  Building2,
  CalendarClock,
  Check,
  CheckCircle2,
  ChevronDown,
  Circle,
  Clipboard,
  Database,
  ExternalLink,
  FileCode,
  FileSpreadsheet,
  FileText,
  Filter,
  Folder,
  FolderOpen,
  FolderTree,
  Hammer,
  Image,
  Inbox,
  Info,
  KeyRound,
  Keyboard,
  Lightbulb,
  Link2,
  ListChecks,
  Lock,
  Microscope,
  Monitor,
  MonitorCog,
  Package,
  PartyPopper,
  PencilLine,
  Plus,
  Puzzle,
  ReceiptText,
  Ruler,
  Save,
  ScrollText,
  Search,
  Settings,
  ShieldCheck,
  Shuffle,
  Sparkles,
  Star,
  Tag,
  Trash2,
  TriangleAlert,
  Type,
  Upload,
  Wand2,
  Wrench,
  X,
  Zap,
} from '@lucide/vue'

/** 业务图标名 → Lucide 组件的核心映射（单一事实源） */
export const ICON_REGISTRY: Record<string, Component> = {
  // —— 通用状态 ——
  check: Check,
  x: X,
  alert: TriangleAlert,
  info: Info,
  'check-circle': CheckCircle2,
  'circle-danger': Circle, // blocker 严重度，颜色由 CSS 控制
  'circle-warning': Circle, // warning 严重度
  'circle-info': Circle, // info 严重度
  party: PartyPopper,
  bulb: Lightbulb,
  search: Search,
  trash: Trash2,
  upload: Upload,
  edit: PencilLine,
  wrench: Wrench,
  puzzle: Puzzle,
  keyboard: Keyboard,
  monitor: MonitorCog,
  zap: Zap,
  sparkles: Sparkles,
  plus: Plus,
  'bell-off': BellOff,
  save: Save,
  'external-link': ExternalLink,
  'arrow-right': ArrowRight,
  'chevron-down': ChevronDown,
  hammer: Hammer,
  shield: ShieldCheck,
  wand: Wand2,
  lock: Lock,
  star: Star,
  inbox: Inbox,
  tag: Tag,
  image: Image,
  presentation: Monitor,

  // —— 约束类型（10 个，与 ConstraintNodeLibrary 一一对应）——
  'constraint-notNull': Ban,
  'constraint-unique': KeyRound,
  'constraint-foreignKey': Link2,
  'constraint-allowedValues': ListChecks,
  'constraint-range': Ruler,
  'constraint-conditional': Shuffle,
  'constraint-scripted': ScrollText,
  'constraint-charset': Type,
  'constraint-dateLogic': CalendarClock,
  'constraint-composite': Package,

  // —— 转换分类（5 个，与 transformCategory.ts 一一对应）——
  'transform-text': FileText,
  'transform-numeric': Binary,
  'transform-cleaning': Brush,
  'transform-structure': Building2,
  'transform-date': CalendarClock,

  // —— 数据源/文件类型 ——
  folder: Folder,
  'folder-open': FolderOpen,
  file: FileText,
  'file-code': FileCode,
  'file-chart': FileSpreadsheet,
  'file-default': FileText,
  database: Database,
  archive: Archive,
  boxes: Boxes,
  'folder-tree': FolderTree,
  filter: Filter,
  receipt: ReceiptText,
  clipboard: Clipboard,

  // —— 节点类型 ——
  'project-root': Microscope,
  gear: Settings,
  'pattern-toolbox': Wrench,
  package: Package,
}

/** 根据业务图标名获取 Lucide 组件。找不到返回 undefined。 */
export function getIcon(name: string): Component | undefined {
  return ICON_REGISTRY[name]
}

/** 约束类型 → 图标名（供 ConstraintNodeLibrary 等数据层使用） */
export const CONSTRAINT_ICON_NAMES: Record<string, string> = {
  notNull: 'constraint-notNull',
  unique: 'constraint-unique',
  foreignKey: 'constraint-foreignKey',
  allowedValues: 'constraint-allowedValues',
  range: 'constraint-range',
  conditional: 'constraint-conditional',
  scripted: 'constraint-scripted',
  charset: 'constraint-charset',
  dateLogic: 'constraint-dateLogic',
  composite: 'constraint-composite',
}

/** 转换分类 id → 图标名（供 transformCategory.ts 等使用） */
export const TRANSFORM_CATEGORY_ICON_NAMES: Record<string, string> = {
  text: 'transform-text',
  numeric: 'transform-numeric',
  cleaning: 'transform-cleaning',
  structure: 'transform-structure',
  date: 'transform-date',
}
