import type { Component } from 'vue'
import {
  Archive,
  ArrowDown,
  ArrowDownUp,
  ArrowRight,
  ArrowUp,
  Ban,
  BellOff,
  Binary,
  BookOpen,
  Boxes,
  Brain,
  Brush,
  Building2,
  Calculator,
  CalendarClock,
  Check,
  CheckCircle2,
  ChevronDown,
  Circle,
  Clipboard,
  Clock,
  Combine,
  Copy,
  CopyX,
  Crop,
  Database,
  Divide,
  Droplet,
  Eraser,
  ExternalLink,
  FileCode,
  FileSpreadsheet,
  FileText,
  Filter,
  Folder,
  FolderOpen,
  FolderTree,
  GitBranch,
  Hammer,
  Hash,
  Image,
  Inbox,
  Info,
  KeyRound,
  Keyboard,
  Layers,
  Lightbulb,
  Link2,
  ListChecks,
  Lock,
  Map,
  Microscope,
  Monitor,
  MonitorCog,
  Package,
  PartyPopper,
  PencilLine,
  Plus,
  Puzzle,
  ReceiptText,
  Regex,
  Replace,
  Ruler,
  Save,
  Scissors,
  ScrollText,
  Search,
  Settings,
  ShieldCheck,
  Shuffle,
  Sigma,
  Sparkles,
  Star,
  Tag,
  Trash2,
  TriangleAlert,
  Type,
  Upload,
  Wand2,
  Wrench,
  X,
  Zap,
} from '@lucide/vue'

/** 业务图标名 → Lucide 组件的核心映射（单一事实源） */
export const ICON_REGISTRY: Record<string, Component> = {
  // —— 通用状态 ——
  check: Check,
  x: X,
  alert: TriangleAlert,
  info: Info,
  'check-circle': CheckCircle2,
  clock: Clock,
  // 通用圆圈：用作中性/草稿状态（颜色由 CSS 控制）。严重度变体见下方。
  circle: Circle,
  'circle-danger': Circle, // blocker 严重度，颜色由 CSS 控制
  'circle-warning': Circle, // warning 严重度
  'circle-info': Circle, // info 严重度
  party: PartyPopper,
  bulb: Lightbulb,
  search: Search,
  trash: Trash2,
  upload: Upload,
  edit: PencilLine,
  wrench: Wrench,
  puzzle: Puzzle,
  keyboard: Keyboard,
  monitor: MonitorCog,
  zap: Zap,
  sparkles: Sparkles,
  plus: Plus,
  'bell-off': BellOff,
  save: Save,
  'external-link': ExternalLink,
  'arrow-right': ArrowRight,
  'chevron-down': ChevronDown,
  hammer: Hammer,
  shield: ShieldCheck,
  wand: Wand2,
  lock: Lock,
  star: Star,
  inbox: Inbox,
  tag: Tag,
  image: Image,
  link: Link2,
  brain: Brain,
  presentation: Monitor,

  // —— 约束类型（10 个，与 ConstraintNodeLibrary 一一对应）——
  'constraint-notNull': Ban,
  'constraint-unique': KeyRound,
  'constraint-foreignKey': Link2,
  'constraint-allowedValues': ListChecks,
  'constraint-range': Ruler,
  'constraint-conditional': Shuffle,
  'constraint-scripted': ScrollText,
  'constraint-charset': Type,
  'constraint-dateLogic': CalendarClock,
  'constraint-composite': Package,

  // —— 转换分类（5 个，与 transformCategory.ts 一一对应）——
  'transform-text': FileText,
  'transform-numeric': Binary,
  'transform-cleaning': Brush,
  'transform-structure': Building2,
  'transform-date': CalendarClock,

  // —— 转换类型（22 个，与 TransformTypeV2 一一对应）——
  'transform-stringSplit': Scissors,
  'transform-regexExtract': Regex,
  'transform-mathExpr': Calculator,
  'transform-dateFormat': CalendarClock,
  'transform-lookup': BookOpen,
  'transform-strip': Eraser,
  'transform-upperCase': ArrowUp,
  'transform-lowerCase': ArrowDown,
  'transform-replace': Replace,
  'transform-filterRows': Filter,
  'transform-fillNA': Droplet,
  'transform-dropDuplicates': CopyX,
  'transform-castType': Binary,
  'transform-concat': Combine,
  'transform-substring': Crop,
  'transform-aggregate': Layers,
  'transform-conditionalAssign': GitBranch,
  'transform-sortRows': ArrowDownUp,
  'transform-digits': Hash,
  'transform-weightedSum': Sigma,
  'transform-modulo': Divide,
  'transform-mapValue': Map,

  // —— 数据源/文件类型 ——
  folder: Folder,
  'folder-open': FolderOpen,
  file: FileText,
  'file-code': FileCode,
  'file-chart': FileSpreadsheet,
  'file-default': FileText,
  database: Database,
  archive: Archive,
  boxes: Boxes,
  'folder-tree': FolderTree,
  filter: Filter,
  receipt: ReceiptText,
  clipboard: Clipboard,
  copy: Copy,
  // 禁用/断开：数据源下拉"断开连接"项
  ban: Ban,

  // —— 节点类型 ——
  'project-root': Microscope,
  gear: Settings,
  'pattern-toolbox': Wrench,
  package: Package,
}

/** 根据业务图标名获取 Lucide 组件。找不到返回 undefined。 */
export function getIcon(name: string): Component | undefined {
  return ICON_REGISTRY[name]
}

/** 约束类型 → 图标名（供 ConstraintNodeLibrary 等数据层使用） */
export const CONSTRAINT_ICON_NAMES = {
  notNull: 'constraint-notNull',
  unique: 'constraint-unique',
  foreignKey: 'constraint-foreignKey',
  allowedValues: 'constraint-allowedValues',
  range: 'constraint-range',
  conditional: 'constraint-conditional',
  scripted: 'constraint-scripted',
  charset: 'constraint-charset',
  dateLogic: 'constraint-dateLogic',
  composite: 'constraint-composite',
} as const satisfies Record<string, string>

/** 转换分类 id → 图标名（供 transformCategory.ts 等使用） */
export const TRANSFORM_CATEGORY_ICON_NAMES = {
  text: 'transform-text',
  numeric: 'transform-numeric',
  cleaning: 'transform-cleaning',
  structure: 'transform-structure',
  date: 'transform-date',
} as const satisfies Record<string, string>

/** 转换类型 → 图标名（与 TransformTypeV2 一一对应，供 transformCategory 等使用） */
export const TRANSFORM_TYPE_ICON_NAMES = {
  StringSplit: 'transform-stringSplit',
  RegexExtract: 'transform-regexExtract',
  MathExpr: 'transform-mathExpr',
  DateFormat: 'transform-dateFormat',
  Lookup: 'transform-lookup',
  Strip: 'transform-strip',
  UpperCase: 'transform-upperCase',
  LowerCase: 'transform-lowerCase',
  Replace: 'transform-replace',
  FilterRows: 'transform-filterRows',
  FillNA: 'transform-fillNA',
  DropDuplicates: 'transform-dropDuplicates',
  CastType: 'transform-castType',
  Concat: 'transform-concat',
  Substring: 'transform-substring',
  Aggregate: 'transform-aggregate',
  ConditionalAssign: 'transform-conditionalAssign',
  SortRows: 'transform-sortRows',
  Digits: 'transform-digits',
  WeightedSum: 'transform-weightedSum',
  Modulo: 'transform-modulo',
  MapValue: 'transform-mapValue',
} as const satisfies Record<string, string>
